# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-26 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certeon', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsLetterForm',
            new_name='NewsLetterRecipients',
        ),
    ]
