# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-26 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certeon', '0003_auto_20190926_0854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsusers',
            options={'verbose_name': 'NewsUser', 'verbose_name_plural': 'NewsUsers'},
        ),
    ]
